/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubmitImport } from './routes/submit'
import { Route as IndexImport } from './routes/index'
import { Route as WorkflowSlugImport } from './routes/workflow.$slug'
import { Route as CategoryCategoryImport } from './routes/category.$category'

// Create/Update Routes

const SubmitRoute = SubmitImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkflowSlugRoute = WorkflowSlugImport.update({
  id: '/workflow/$slug',
  path: '/workflow/$slug',
  getParentRoute: () => rootRoute,
} as any)

const CategoryCategoryRoute = CategoryCategoryImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitImport
      parentRoute: typeof rootRoute
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryImport
      parentRoute: typeof rootRoute
    }
    '/workflow/$slug': {
      id: '/workflow/$slug'
      path: '/workflow/$slug'
      fullPath: '/workflow/$slug'
      preLoaderRoute: typeof WorkflowSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/workflow/$slug': typeof WorkflowSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/workflow/$slug': typeof WorkflowSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/workflow/$slug': typeof WorkflowSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/submit' | '/category/$category' | '/workflow/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/submit' | '/category/$category' | '/workflow/$slug'
  id: '__root__' | '/' | '/submit' | '/category/$category' | '/workflow/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubmitRoute: typeof SubmitRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  WorkflowSlugRoute: typeof WorkflowSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubmitRoute: SubmitRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  WorkflowSlugRoute: WorkflowSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/submit",
        "/category/$category",
        "/workflow/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/submit": {
      "filePath": "submit.tsx"
    },
    "/category/$category": {
      "filePath": "category.$category.tsx"
    },
    "/workflow/$slug": {
      "filePath": "workflow.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
